### ISSUE TITLE
数据

### ISSUE THREAD

**Issue by WallZFE** [wish44165/One-Epoch-Training-for-Object-Detection-in-Fisheye-Images#1]
祝贺你们取得第四名的成绩，真的很厉害。您方便分享一下你们使用的鱼眼数据集吗？我现在在研究鱼眼检测，在网上找数据只找到woodscape数据集。十分感谢

**Comment by wish44165** [comment]
@WallZFE Thanks for your support.
Below are some fisheye datasets and references for conversion methods.
WoodScape: https://github.com/valeoai/WoodScape
FishEye8K: https://github.com/MoyoG/FishEye8K
iVS-Dataset: https://pairlabs.nycu.edu.tw:52959/?p=28
Conversion Tool for FishEye Dataset: https://github.com/leofansq/Tools_KITTI2FishEye
Apply Fish Eye effect to your photos: https://github.com/Gil-Mor/iFish
Please feel free to ask if you have additional questions.

**Comment by WallZFE** [comment]
Thank you
